# Generated by Django 4.0.3 on 2022-04-30 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('PR', 'Paraná'), ('SP', 'São Paulo'), ('SC', 'Santa Catarina')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(help_text='Digite seu nome completo', max_length=50, verbose_name='Qual seu nome?')),
                ('nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Paginas.cidade')),
            ],
        ),
    ]
