# Generated by Django 4.0.4 on 2022-05-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paginas', '0002_banco_tipoconta_alter_pessoa_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='nascimento',
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome_completo',
            field=models.CharField(help_text='Digite seu nome completo', max_length=50, verbose_name='Nome'),
        ),
        migrations.DeleteModel(
            name='Cidade',
        ),
    ]
