# Generated by Django 4.0.4 on 2022-05-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paginas', '0003_remove_pessoa_cidade_remove_pessoa_nascimento_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoConta',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='email',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(blank=True, help_text='Digite seu nome telefone', max_length=11, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome_completo',
            field=models.CharField(help_text='Digite seu nome completo', max_length=50, verbose_name='Nome Completo'),
        ),
    ]
