# Generated by Django 4.0.4 on 2022-05-23 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paginas', '0004_delete_tipoconta_remove_pessoa_email_pessoa_telefone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='TipoOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
            ],
        ),
    ]
