# Generated by Django 4.0.4 on 2022-06-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paginas', '0005_categoria_tipooperacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
            ],
        ),
    ]
