# Generated by Django 4.0.4 on 2022-06-20 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Paginas', '0007_movimentacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(default='000.000.000-00', max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='usuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(blank=True, help_text='Digite seu nome telefone', max_length=15, null=True, verbose_name='Telefone'),
        ),
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.CharField(max_length=50, verbose_name='Agência')),
                ('conta', models.CharField(max_length=10)),
                ('valor_total', models.DecimalField(decimal_places=0, max_digits=9999999)),
                ('conjunta', models.BooleanField()),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Paginas.banco')),
                ('tipo_conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Paginas.tipoconta')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
