# Generated by Django 4.0.4 on 2022-07-05 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paginas', '0010_remove_movimentacao_tipo_operacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=0, max_digits=50)),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipo_movimetacao',
            field=models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], default='S', max_length=2),
        ),
        migrations.DeleteModel(
            name='Movimentacao',
        ),
        migrations.AddField(
            model_name='movimentacaoentrada',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Paginas.categoria'),
        ),
        migrations.AddField(
            model_name='movimentacaoentrada',
            name='conta_bancaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Paginas.contabancaria', verbose_name='Conta Bancária'),
        ),
    ]
