# Generated by Django 4.0.4 on 2022-07-18 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paginas', '0011_movimentacaoentrada_alter_categoria_tipo_movimetacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoSaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=0, max_digits=50)),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Paginas.categoria')),
                ('conta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Paginas.contabancaria', verbose_name='Conta Bancária')),
            ],
        ),
    ]
