# Generated by Django 4.0.4 on 2022-08-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paginas', '0012_movimentacaosaida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoentrada',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name='movimentacaosaida',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
