# Generated by Django 4.0.4 on 2022-08-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paginas', '0013_alter_movimentacaoentrada_valor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contabancaria',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=99999999999),
        ),
    ]
