# Generated by Django 4.0.4 on 2022-08-22 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paginas', '0014_alter_contabancaria_valor_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoExtrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=50)),
                ('conta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Paginas.contabancaria', verbose_name='Conta Bancária')),
            ],
        ),
    ]
