# Generated by Django 4.0.4 on 2022-08-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paginas', '0015_historicoextrato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicoextrato',
            old_name='valor',
            new_name='valor_conta_antigo',
        ),
        migrations.AddField(
            model_name='historicoextrato',
            name='valor_conta_atual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicoextrato',
            name='valor_movimentacao',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=50),
            preserve_default=False,
        ),
    ]
