# Generated by Django 4.0.4 on 2022-08-23 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paginas', '0016_rename_valor_historicoextrato_valor_conta_antigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoextrato',
            name='conta_bancaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paginas.contabancaria', verbose_name='Conta Bancária'),
        ),
    ]
