# Generated by Django 4.0.4 on 2022-09-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paginas', '0017_alter_historicoextrato_conta_bancaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoextrato',
            name='tipo_movimetacao',
            field=models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], default='S', max_length=2),
        ),
    ]
